using GameStudioClicker.Core.Models;
using GameStudioClicker.Wpf.Commands;
using GameStudioClicker.Wpf.Formatting;
using System.Windows.Threading;

namespace GameStudioClicker.Wpf.ViewModels;

public class MainViewModel : ViewModelBase, IDisposable
{
    private readonly GameState _gameState;
    private readonly DispatcherTimer _passiveTimer;
    private readonly DispatcherTimer _offlineMessageTimer;
    private readonly DispatcherTimer _saveConfirmationMessageTimer;

    // Achievement notification system
    private readonly DispatcherTimer _achievementNotificationTimer;
    private readonly Queue<Achievement> _achievementNotificationQueue = new();
    private Achievement? _currentAchievementNotification;

    // View state
    private GamePage _selectedPage = GamePage.Workers;
    private bool _showOfflineEarnings;
    private bool _showSaveConfirmation;
    private bool _isDisposed;

    public MainViewModel(GameState gameState, long offlineLinesEarned = 0)
    {
        _gameState = gameState ?? throw new ArgumentNullException(nameof(gameState));

        var activeUpgradeViewModels = new List<ActiveUpgradeViewModel>();
        foreach (ActiveUpgrade upgrade in _gameState.ActiveUpgrades)
        {
            activeUpgradeViewModels.Add(new ActiveUpgradeViewModel(_gameState, upgrade));
        }

        ActiveUpgrades = activeUpgradeViewModels;
        RefreshActiveUpgradeVisibility();

        var workerUpgradeViewModels = new List<WorkerUpgradeViewModel>();
        foreach (WorkerUpgrade upgrade in _gameState.WorkerUpgrades)
        {
            workerUpgradeViewModels.Add(new WorkerUpgradeViewModel(_gameState, upgrade));
        }

        WorkerUpgrades = workerUpgradeViewModels;

        var achievementViewModels = new List<AchievementViewModel>();
        foreach (Achievement achievement in _gameState.Achievements)
        {
            achievementViewModels.Add(new AchievementViewModel(_gameState, achievement));
        }

        Achievements = achievementViewModels;

        Statistics = CreateStatistics(_gameState);

        OfflineLinesEarned = Math.Max(0, offlineLinesEarned);
        _showOfflineEarnings = OfflineLinesEarned > 0;

        _offlineMessageTimer = new DispatcherTimer
        {
            Interval = TimeSpan.FromSeconds(7)
        };
        _offlineMessageTimer.Tick += OfflineMessageTimer_Tick;

        _passiveTimer = new DispatcherTimer
        {
            Interval = TimeSpan.FromSeconds(1)
        };
        _passiveTimer.Tick += PassiveTimer_Tick;

        _saveConfirmationMessageTimer = new DispatcherTimer
        {
            Interval = TimeSpan.FromSeconds(1.5)
        };
        _saveConfirmationMessageTimer.Tick += SaveConfirmationMessage_Tick;

        _achievementNotificationTimer = new DispatcherTimer
        {
            Interval = TimeSpan.FromSeconds(4)
        };
        _achievementNotificationTimer.Tick += AchievementNotificationTimer_Tick;
        _gameState.AchievementEarned += GameState_AchievementEarned;

        WriteCodeCommand = new RelayCommand(ExecuteWriteCode);
        PurchaseActiveUpgradeCommand = new RelayCommand(
            ExecutePurchaseActiveUpgrade,
            CanExecutePurchaseActiveUpgrade);
        PurchaseWorkerUpgradeCommand = new RelayCommand(
            ExecutePurchaseWorkerUpgrade,
            CanExecutePurchaseWorkerUpgrade);
        ToggleStatisticsCommand = new RelayCommand(ExecuteToggleStatistics);
        ToggleAchievementsCommand = new RelayCommand(ExecuteToggleAchievements);

        if (_showOfflineEarnings)
        {
            _offlineMessageTimer.Start();
        }

        _passiveTimer.Start();
    }


    private static IReadOnlyList<StatisticViewModel> CreateStatistics(
        GameState gameState)
    {
        return
            [
                new StatisticViewModel("Lines of Code", () => gameState.LifetimeLinesOfCode),
                new StatisticViewModel("Manual Clicks", () => gameState.LifetimeManualClicks),
                new StatisticViewModel("Employees Hired", () => gameState.LifetimeEmployeesHired),
                new StatisticViewModel("Active Upgrades Purchased", () => gameState.LifetimeActiveUpgradesPurchased),
                new StatisticViewModel("Lines Generated Manually", () => gameState.LinesGeneratedManually),
                new StatisticViewModel("Lines Generated by Workers", () => gameState.LinesGeneratedByWorkers),
                new StatisticViewModel("Lines Generated While Online", () => gameState.LinesGeneratedWhileOnline),
                new StatisticViewModel("Lines Generated While Offline", () => gameState.LinesGeneratedWhileOffline)
            ];
    }

    // Production displayed by the main coding panel.
    public long LinesOfCode => _gameState.LinesOfCode;
    public long LinesPerClick => _gameState.LinesPerClick;
    public long LinesPerSecond => _gameState.LinesPerSecond;

    // Navigation and view state
    public bool IsStatisticsViewVisible =>
        _selectedPage == GamePage.Statistics;
    public bool IsAchievementsViewVisible =>
        _selectedPage == GamePage.Achievements;

    // One-time notifications.
    public long OfflineLinesEarned { get; }
    public bool HasOfflineEarnings => _showOfflineEarnings;
    public string OfflineEarningsMessage =>
        $"Your Employees wrote {CompactNumberFormatter.Format(OfflineLinesEarned)} lines of code while you were away!";
    public bool HasSaveConfirmation => _showSaveConfirmation;
    public bool HasAchievementNotification =>
        _currentAchievementNotification != null;
    public string AchievementNotificationName =>
        _currentAchievementNotification?.DisplayName ?? string.Empty;
    public string AchievementNotificationDescription =>
        _currentAchievementNotification?.Description ?? string.Empty;

    // Collections and commands consumed by the view.
    public IReadOnlyList<ActiveUpgradeViewModel> ActiveUpgrades { get; }
    public IReadOnlyList<WorkerUpgradeViewModel> WorkerUpgrades { get; }
    public IReadOnlyList<AchievementViewModel> Achievements { get; }
    public IReadOnlyList<StatisticViewModel> Statistics { get; }
    public RelayCommand WriteCodeCommand { get; }
    public RelayCommand PurchaseActiveUpgradeCommand { get; }
    public RelayCommand PurchaseWorkerUpgradeCommand { get; }
    public RelayCommand ToggleStatisticsCommand { get; }
    public RelayCommand ToggleAchievementsCommand { get; }

    public event EventHandler? SaveRequested;
    public event EventHandler? AchievementNotificationShown;

    public void ShowSaveConfirmation()
    {
        _showSaveConfirmation = true;
        OnPropertyChanged(nameof(HasSaveConfirmation));

        // Restarting the timer keeps the message visible after closely spaced saves.
        _saveConfirmationMessageTimer.Stop();
        _saveConfirmationMessageTimer.Start();
    }

    public void Dispose()
    {
        if (_isDisposed)
        {
            return;
        }

        _isDisposed = true;

        _offlineMessageTimer.Stop();
        _offlineMessageTimer.Tick -= OfflineMessageTimer_Tick;

        _passiveTimer.Stop();
        _passiveTimer.Tick -= PassiveTimer_Tick;

        _saveConfirmationMessageTimer.Stop();
        _saveConfirmationMessageTimer.Tick -= SaveConfirmationMessage_Tick;

        _gameState.AchievementEarned -= GameState_AchievementEarned;

        _achievementNotificationTimer.Stop();
        _achievementNotificationTimer.Tick -= AchievementNotificationTimer_Tick;
    }

    private void ExecuteWriteCode(object? parameter)
    {
        _gameState.WriteCode();
        RefreshAll();
    }

    private bool CanExecutePurchaseActiveUpgrade(object? parameter)
    {
        if (parameter is ActiveUpgradeViewModel upgradeViewModel)
        {
            return _gameState.CanPurchaseActiveUpgrade(upgradeViewModel.Upgrade);
        }

        return false;
    }

    private void ExecutePurchaseActiveUpgrade(object? parameter)
    {
        if (parameter is ActiveUpgradeViewModel upgradeViewModel &&
            _gameState.TryPurchaseActiveUpgrade(upgradeViewModel.Upgrade))
        {

            SaveRequested?.Invoke(this, new EventArgs());

            RefreshAll();
        }
    }

    private bool CanExecutePurchaseWorkerUpgrade(object? parameter)
    {
        if (parameter is WorkerUpgradeViewModel upgradeViewModel)
        {
            return _gameState.CanPurchaseWorkerUpgrade(upgradeViewModel.Upgrade);
        }

        return false;
    }

    private void ExecutePurchaseWorkerUpgrade(object? parameter)
    {
        if (parameter is WorkerUpgradeViewModel upgradeViewModel &&
            _gameState.TryPurchaseWorkerUpgrade(upgradeViewModel.Upgrade))
        {
            SaveRequested?.Invoke(this, new EventArgs());

            RefreshAll();
        }
    }

    private void ExecuteToggleStatistics(object? parameter)
    {
        TogglePage(GamePage.Statistics);
    }

    private void ExecuteToggleAchievements(object? parameter)
    {
        TogglePage(GamePage.Achievements);
    }

    private void PassiveTimer_Tick(object? sender, EventArgs e)
    {
        _gameState.GeneratePassiveLines();

        RefreshAll();
    }

    private void OfflineMessageTimer_Tick(object? sender, EventArgs e)
    {
        _offlineMessageTimer.Stop();
        _showOfflineEarnings = false;
        OnPropertyChanged(nameof(HasOfflineEarnings));
    }

    private void SaveConfirmationMessage_Tick(object? sender, EventArgs e)
    {
        _saveConfirmationMessageTimer.Stop();
        _showSaveConfirmation = false;
        OnPropertyChanged(nameof(HasSaveConfirmation));
    }

    private void GameState_AchievementEarned(Achievement achievement)
    {
        _achievementNotificationQueue.Enqueue(achievement);

        if (_currentAchievementNotification is null)
        {
            ShowNextAchievementNotification();
        }
    }

    private void AchievementNotificationTimer_Tick(object? sender, EventArgs e)
    {
        // Each notification should only remain visible for one timer interval.
        _achievementNotificationTimer.Stop();

        // Hide the current notification and reset the XAML DataTrigger.
        // The trigger must become false before the next notification is shown,
        // otherwise its entrance animation will not run again.
        _currentAchievementNotification = null;
        RefreshAchievementNotificationState();


        if (_achievementNotificationQueue.Count > 0)
        {
            // Show the next notification on the next UI pass. This gives WPF time
            // to process the hidden state before HasAchievementNotification becomes
            // true again and restarts the entrance animation.
            Dispatcher.CurrentDispatcher.BeginInvoke(
                new Action(ShowNextAchievementNotification));
        }
    }

    private void ShowNextAchievementNotification()
    {
        _achievementNotificationTimer.Stop();

        _currentAchievementNotification =
            _achievementNotificationQueue.Count > 0
                ? _achievementNotificationQueue.Dequeue()
                : null;

        RefreshAchievementNotificationState();

        if (_currentAchievementNotification is not null)
        {
            _achievementNotificationTimer.Start();
            AchievementNotificationShown?.Invoke(this, EventArgs.Empty);
        }
    }

    private void RefreshProductionValues()
    {
        OnPropertyChanged(nameof(LinesOfCode));
        OnPropertyChanged(nameof(LinesPerClick));
        OnPropertyChanged(nameof(LinesPerSecond));
    }

    private void RefreshPurchaseCommands()
    {
        PurchaseActiveUpgradeCommand.RaiseCanExecuteChanged();
        PurchaseWorkerUpgradeCommand.RaiseCanExecuteChanged();
    }

    private void RefreshActiveUpgradeStates()
    {
        foreach (ActiveUpgradeViewModel upgradeViewModel in ActiveUpgrades)
        {
            upgradeViewModel.RefreshState();
        }

        RefreshActiveUpgradeVisibility();
    }

    private void RefreshWorkerUpgradeStates()
    {
        foreach (WorkerUpgradeViewModel upgradeViewModel in WorkerUpgrades)
        {
            upgradeViewModel.RefreshState();
        }
    }

    private void RefreshAchievements()
    {
        foreach (AchievementViewModel achievement in Achievements)
        {
            achievement.RefreshState();
        }
    }

    private void RefreshAchievementNotificationState()
    {
        OnPropertyChanged(nameof(HasAchievementNotification));
        OnPropertyChanged(nameof(AchievementNotificationName));
        OnPropertyChanged(nameof(AchievementNotificationDescription));
    }

    private void RefreshViewStates()
    {
        OnPropertyChanged(nameof(IsStatisticsViewVisible));
        OnPropertyChanged(nameof(IsAchievementsViewVisible));
    }

    private void RefreshStatistics()
    {
        foreach (var statistic in Statistics)
        {
            statistic.Refresh();
        }
    }

    private void RefreshAll()
    {
        RefreshProductionValues();
        RefreshWorkerUpgradeStates();
        RefreshActiveUpgradeStates();
        RefreshPurchaseCommands();
        RefreshAchievements();
        RefreshStatistics();
    }

    private void RefreshActiveUpgradeVisibility()
    {
        int visibleUpgradeCount = 0;

        foreach (ActiveUpgradeViewModel upgradeViewModel in ActiveUpgrades)
        {
            bool shouldBeVisible =
                !upgradeViewModel.IsPurchased &&
                visibleUpgradeCount < 3;

            upgradeViewModel.UpdateVisibility(shouldBeVisible);

            if (shouldBeVisible)
            {
                visibleUpgradeCount++;
            }
        }
    }

    private void TogglePage(GamePage page)
    {
        // If the user clicks the currently selected page, return to the default Workers page. Otherwise change to the clicked page.
        GamePage nextPage =
            _selectedPage == page ? GamePage.Workers : page;

        if (_selectedPage == nextPage)
        {
            return;
        }

        _selectedPage = nextPage;
        RefreshViewStates();
    }
}
