<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Remove="Assets\**\*.png" />
    <Resource Include="Assets\**\*.png" />
	  
    <None Remove="Assets\Fonts\**\*.ttf" />
    <Resource Include="Assets\Fonts\**\*.ttf" />

	  <None Update="Assets\Audio\**\*.wav">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  
    <ProjectReference Include="..\GameStudioClicker.Core\GameStudioClicker.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Audio\Music\" />
    <Folder Include="Assets\Audio\SFX\" />
    <Folder Include="Assets\Fonts\Inter\" />
    <Folder Include="Assets\Fonts\PressStart2P\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
